In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5]) # Create a 1-dimensional array
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]]) # Create a 2-dimensional array
print(b)

mean_a = np.mean(a) # Calculate the mean of the array a
print(mean_a)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
3.0
